version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  # frontend-tests:
  #   image: docker-compose-demo_frontend
  #   volumes:
  #     - ./frontend:/app
  #   command: npm test
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://database/todo
    volumes:
      - ./backend:/app
    command: ./docker-entrypoint.sh
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - todo:/data/db

volumes:
  todo: {}
