version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:3000
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://database/todo
    command: ./docker-entrypoint.sh
    restart: unless-stopped
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - todo:/data/db
    restart: unless-stopped

volumes:
  todo:
